#!/bin/python3

import sys
import math


t = int(input().strip())
for a0 in range(t):
    n = int(input().strip())
    lcm = 1

    for i in range(2, n + 1):
        lcm = lcm * i // math.gcd(lcm, i)

    print(lcm)
